name: Inter-branch merge workflow
on:
  push:
    branches:
      - release/**

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  Merge:
    uses: dotnet/arcade/.github/workflows/inter-branch-merge-base.yml@552263a656c5896aeeb930e65172bb8a2bb7b996 # 2024-06-24
